CREATE FUNCTION GETNTHHIGHESTSALARY(N INT) RETURNS 
INT BEGIN 
	SELECT N -1 INTO N;
	RETURN (
	        SELECT DISTINCT salary
	        FROM `Employee`
	        ORDER BY salary DESC
	        LIMIT 1
	        OFFSET N
	    );
END; 